### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by haldi4803** [ClimbSnail/HoloCubic_AIO_Tool#1]
Hi,

Tried to start the tool in windows 10

![image](https://user-images.githubusercontent.com/17104473/197346831-cb1d1fd3-aec1-4ee4-87eb-1a8e5e2b338b.png)

Traceback (most recent call last):
  File "CubicAIO_Tool.py", line 159, in <module>
    engine = Engine(tool_windows)
  File "CubicAIO_Tool.py", line 61, in __init__
    self.m_setting_tab_windows = Setting(self.m_setting_tab, self)
  File "page\setting.py", line 45, in __init__
    fp = codecs.open(self.cfg_name, "r", "utf8")
  File "codecs.py", line 905, in open
FileNotFoundError: [Errno 2] No such file or directory: 'cubictool.json'

python 3.10 is installed.

**Comment by ClimbSnail** [comment]
新修改的部分遗漏了同步，目前可以从 https://github.com/ClimbSnail/HoloCubic_AIO 中的 AIO_Tool目录下载上位机的最新源码

**Comment by haldi4803** [comment]
Including a precompiled firmware.bin ?

**Comment by ClimbSnail** [comment]
> Including a precompiled firmware.bin ?

Yes. firmware.bin is always updated, so it is not placed in the upper computer.

**Comment by ClimbSnail** [comment]
> Including a precompiled firmware.bin ?

You can use the replacement in https://github.com/ClimbSnail/HoloCubic_AIO/releases/tag/v2.1.0%E5%9B%BA%E4%BB%B6
